#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SportNet.Resource", IsApplication=true)]

namespace SportNet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::SportNet.Resource.String.library_name;
			global::SportNet.Web.Models.Android.Resource.String.library_name = global::SportNet.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adUnitId = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int cameraBearing = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTargetLat = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLng = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTilt = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraZoom = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int mapType = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int uiCompass = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiRotateGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiScrollGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiTiltGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomControls = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomGestures = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int useViewLifecycle = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int zOrderOnTop = 2130771983;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int common_signin_btn_text_dark = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_signin_btn_text_light = 2130968587;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionBar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionBarDivider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int activeDot = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int backSmall = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int baloon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int beerbottle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bgr = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int blackOverlay = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int buttonlong = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int buttonlongwhite = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int check = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int checkred = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int choose = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int comment = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_disabled_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_disabled_focus_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_icon_disabled_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_icon_focus_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_icon_focus_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_icon_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_icon_normal_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_icon_normal_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_icon_pressed_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_icon_pressed_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_disabled_dark = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_disabled_focus_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_disabled_focus_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_text_disabled_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_text_focus_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_text_focus_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_text_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_text_normal_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_text_normal_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_signin_btn_text_pressed_dark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_signin_btn_text_pressed_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int createAnAcc = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int dropDown = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int email = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int FacebookGrey = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int facebookLike = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int footballIcon = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int FootballSelection = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int GooglePlusGrey = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int gPlusAdd = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int grid_state = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int gridview_highlight_selector = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_plusone_medium_off_client = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_plusone_small_off_client = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_plusone_standard_off_client = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_plusone_tall_off_client = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int indicator = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int lewandovski = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int lineDark = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int lineLight = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int lineSeparator = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int livescore = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int livescore_state = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int livescoreActive = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int loginToSportNet = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int logoSportNet = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int menu = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int menuSmall = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int Messi = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int messibarcelona = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int news = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int news_state = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int newsActive = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int normalDot = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int photo = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int photoBig = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int photoSmall = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int pictures = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int pictures_state = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int picturesActive = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int play = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int plus = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int plusWhite = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int profile = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int profilebig = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int redFrame = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int redOverlay = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int splashSmall = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int SportNet = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int SportNetNoPic = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int SportNetNoPicBig = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int textInputBackground = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int TwitterGrey = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int twitterTweet = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int video = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int video_state = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int videoActive = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int wall = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int yesterday = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int yesterday_state = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int yesterdayActive = 2130837603;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001b
			public const int AboutAppButton = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int ActionBarBack = 2131034142;
			
			// aapt resource value: 0x7f050021
			public const int ActionBarLogo = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int ActionBarMenu = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int ActionBarSportNet = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int ActionBarTitle = 2131034144;
			
			// aapt resource value: 0x7f050078
			public const int AdWebView = 2131034232;
			
			// aapt resource value: 0x7f050055
			public const int AddContent = 2131034197;
			
			// aapt resource value: 0x7f050006
			public const int Background = 2131034118;
			
			// aapt resource value: 0x7f05009d
			public const int Category = 2131034269;
			
			// aapt resource value: 0x7f05002d
			public const int CellLayout = 2131034157;
			
			// aapt resource value: 0x7f050027
			public const int Change = 2131034151;
			
			// aapt resource value: 0x7f050018
			public const int ChangePasswordButton = 2131034136;
			
			// aapt resource value: 0x7f050033
			public const int Checkmark = 2131034163;
			
			// aapt resource value: 0x7f05003e
			public const int Chose = 2131034174;
			
			// aapt resource value: 0x7f050026
			public const int ConfirmPassword = 2131034150;
			
			// aapt resource value: 0x7f050069
			public const int CreateAnAccount = 2131034217;
			
			// aapt resource value: 0x7f050023
			public const int CurrentPassword = 2131034147;
			
			// aapt resource value: 0x7f05002c
			public const int CustomizingCategory = 2131034156;
			
			// aapt resource value: 0x7f050028
			public const int CustomizingSelection = 2131034152;
			
			// aapt resource value: 0x7f050022
			public const int Divider = 2131034146;
			
			// aapt resource value: 0x7f050042
			public const int EditEmail = 2131034178;
			
			// aapt resource value: 0x7f050040
			public const int EditFirstName = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int EditLastName = 2131034177;
			
			// aapt resource value: 0x7f050017
			public const int EditProfileButton = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int Email = 2131034134;
			
			// aapt resource value: 0x7f050044
			public const int FILM = 2131034180;
			
			// aapt resource value: 0x7f050014
			public const int FirstName = 2131034132;
			
			// aapt resource value: 0x7f05004c
			public const int Frame = 2131034188;
			
			// aapt resource value: 0x7f050083
			public const int FullscreenPicture = 2131034243;
			
			// aapt resource value: 0x7f050082
			public const int FullscreenView = 2131034242;
			
			// aapt resource value: 0x7f05004b
			public const int GalleryGridview = 2131034187;
			
			// aapt resource value: 0x7f050047
			public const int GalleryHeading = 2131034183;
			
			// aapt resource value: 0x7f05008f
			public const int Heading = 2131034255;
			
			// aapt resource value: 0x7f05003b
			public const int Image = 2131034171;
			
			// aapt resource value: 0x7f050085
			public const int ImageContainer = 2131034245;
			
			// aapt resource value: 0x7f050015
			public const int LastName = 2131034133;
			
			// aapt resource value: 0x7f050076
			public const int Line = 2131034230;
			
			// aapt resource value: 0x7f050093
			public const int ListLiveScoreToday = 2131034259;
			
			// aapt resource value: 0x7f050099
			public const int ListVideo = 2131034265;
			
			// aapt resource value: 0x7f050092
			public const int ListViewContainer = 2131034258;
			
			// aapt resource value: 0x7f05005d
			public const int Loader = 2131034205;
			
			// aapt resource value: 0x7f05009e
			public const int LocalWebView = 2131034270;
			
			// aapt resource value: 0x7f05006a
			public const int Login = 2131034218;
			
			// aapt resource value: 0x7f050068
			public const int MainLayout = 2131034216;
			
			// aapt resource value: 0x7f050073
			public const int MainMenu = 2131034227;
			
			// aapt resource value: 0x7f050007
			public const int MakeProfilePublic = 2131034119;
			
			// aapt resource value: 0x7f050059
			public const int MakeSportNetYourOwn = 2131034201;
			
			// aapt resource value: 0x7f05006b
			public const int MaybeLater = 2131034219;
			
			// aapt resource value: 0x7f050075
			public const int MenuElement = 2131034229;
			
			// aapt resource value: 0x7f050094
			public const int MenuList = 2131034260;
			
			// aapt resource value: 0x7f050056
			public const int MenuMenu = 2131034198;
			
			// aapt resource value: 0x7f050053
			public const int MenuName = 2131034195;
			
			// aapt resource value: 0x7f050025
			public const int NewPassword = 2131034149;
			
			// aapt resource value: 0x7f05007a
			public const int NewsDetailWebView = 2131034234;
			
			// aapt resource value: 0x7f05007b
			public const int NewsList = 2131034235;
			
			// aapt resource value: 0x7f050019
			public const int NotificationsButton = 2131034137;
			
			// aapt resource value: 0x7f050077
			public const int NumberOfPhotos = 2131034231;
			
			// aapt resource value: 0x7f05004a
			public const int NumberOfPictures = 2131034186;
			
			// aapt resource value: 0x7f050063
			public const int Password = 2131034211;
			
			// aapt resource value: 0x7f050049
			public const int Photo = 2131034185;
			
			// aapt resource value: 0x7f050081
			public const int PictureLayout = 2131034241;
			
			// aapt resource value: 0x7f050084
			public const int PicturesList = 2131034244;
			
			// aapt resource value: 0x7f05000f
			public const int PrivasyPolicy = 2131034127;
			
			// aapt resource value: 0x7f050048
			public const int Provider = 2131034184;
			
			// aapt resource value: 0x7f05001a
			public const int RemoveAccountButton = 2131034138;
			
			// aapt resource value: 0x7f050024
			public const int SecondDivider = 2131034148;
			
			// aapt resource value: 0x7f050034
			public const int SelectionCell = 2131034164;
			
			// aapt resource value: 0x7f050045
			public const int Send = 2131034181;
			
			// aapt resource value: 0x7f050054
			public const int Settings = 2131034196;
			
			// aapt resource value: 0x7f05001c
			public const int SignOutButton = 2131034140;
			
			// aapt resource value: 0x7f050058
			public const int SignUp = 2131034200;
			
			// aapt resource value: 0x7f05008e
			public const int SportContainer = 2131034254;
			
			// aapt resource value: 0x7f050090
			public const int SportIcon = 2131034256;
			
			// aapt resource value: 0x7f050035
			public const int SportImage = 2131034165;
			
			// aapt resource value: 0x7f05002a
			public const int StartReading = 2131034154;
			
			// aapt resource value: 0x7f050088
			public const int Submit = 2131034248;
			
			// aapt resource value: 0x7f05000d
			public const int TermsOfUse = 2131034125;
			
			// aapt resource value: 0x7f05003a
			public const int Text = 2131034170;
			
			// aapt resource value: 0x7f050079
			public const int Text1 = 2131034233;
			
			// aapt resource value: 0x7f050086
			public const int Text2 = 2131034246;
			
			// aapt resource value: 0x7f05003d
			public const int TextCustom1 = 2131034173;
			
			// aapt resource value: 0x7f05003c
			public const int TextCustom2 = 2131034172;
			
			// aapt resource value: 0x7f05008d
			public const int TodayLiveScore = 2131034253;
			
			// aapt resource value: 0x7f050098
			public const int UserCustomizingCategory = 2131034264;
			
			// aapt resource value: 0x7f050097
			public const int UserNewsList = 2131034263;
			
			// aapt resource value: 0x7f05000b
			public const int WriteAppReview = 2131034123;
			
			// aapt resource value: 0x7f05004e
			public const int alpha = 2131034190;
			
			// aapt resource value: 0x7f05000e
			public const int and = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int app = 2131034129;
			
			// aapt resource value: 0x7f050030
			public const int arrow = 2131034160;
			
			// aapt resource value: 0x7f050037
			public const int black = 2131034167;
			
			// aapt resource value: 0x7f050032
			public const int bottom = 2131034162;
			
			// aapt resource value: 0x7f050062
			public const int calltabs_content = 2131034210;
			
			// aapt resource value: 0x7f05002f
			public const int categoryTitle = 2131034159;
			
			// aapt resource value: 0x7f050039
			public const int check = 2131034169;
			
			// aapt resource value: 0x7f05004f
			public const int container = 2131034191;
			
			// aapt resource value: 0x7f050089
			public const int createAccButton = 2131034249;
			
			// aapt resource value: 0x7f050091
			public const int dropDownContainer = 2131034257;
			
			// aapt resource value: 0x7f05005c
			public const int finished = 2131034204;
			
			// aapt resource value: 0x7f05006d
			public const int firstIndicator = 2131034221;
			
			// aapt resource value: 0x7f050008
			public const int followFacebook = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int followGoogle = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int followTwitter = 2131034121;
			
			// aapt resource value: 0x7f050067
			public const int forgotPassButton = 2131034215;
			
			// aapt resource value: 0x7f050070
			public const int fourthIndicator = 2131034224;
			
			// aapt resource value: 0x7f050087
			public const int gallery = 2131034247;
			
			// aapt resource value: 0x7f050029
			public const int gridview = 2131034153;
			
			// aapt resource value: 0x7f05002b
			public const int heading = 2131034155;
			
			// aapt resource value: 0x7f050004
			public const int hybrid = 2131034116;
			
			// aapt resource value: 0x7f05005f
			public const int hyphen = 2131034207;
			
			// aapt resource value: 0x7f050005
			public const int include = 2131034117;
			
			// aapt resource value: 0x7f050071
			public const int kor = 2131034225;
			
			// aapt resource value: 0x7f050010
			public const int left_menu = 2131034128;
			
			// aapt resource value: 0x7f050057
			public const int left_menu_Unsigned = 2131034199;
			
			// aapt resource value: 0x7f050064
			public const int loginButton = 2131034212;
			
			// aapt resource value: 0x7f050065
			public const int loginViaFacebook = 2131034213;
			
			// aapt resource value: 0x7f050066
			public const int loginViaGoogle = 2131034214;
			
			// aapt resource value: 0x7f050050
			public const int mainCategory = 2131034192;
			
			// aapt resource value: 0x7f050072
			public const int mainGallery = 2131034226;
			
			// aapt resource value: 0x7f050051
			public const int mainHeading = 2131034193;
			
			// aapt resource value: 0x7f05004d
			public const int mainPicture = 2131034189;
			
			// aapt resource value: 0x7f050096
			public const int mainPicturesContainer = 2131034262;
			
			// aapt resource value: 0x7f050052
			public const int menuImage = 2131034194;
			
			// aapt resource value: 0x7f05005a
			public const int minutes = 2131034202;
			
			// aapt resource value: 0x7f050000
			public const int none = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int normal = 2131034113;
			
			// aapt resource value: 0x7f050043
			public const int onOffSwitch = 2131034179;
			
			// aapt resource value: 0x7f05007e
			public const int onOffSwitchBreakingStories = 2131034238;
			
			// aapt resource value: 0x7f05007d
			public const int onOffSwitchGetNotifications = 2131034237;
			
			// aapt resource value: 0x7f050080
			public const int onOffSwitchLiveScoreEvents = 2131034240;
			
			// aapt resource value: 0x7f05007f
			public const int onOffSwitchNewSources = 2131034239;
			
			// aapt resource value: 0x7f05006c
			public const int pagerController = 2131034220;
			
			// aapt resource value: 0x7f05009b
			public const int play = 2131034267;
			
			// aapt resource value: 0x7f050038
			public const int plus = 2131034168;
			
			// aapt resource value: 0x7f050031
			public const int plusWhite = 2131034161;
			
			// aapt resource value: 0x7f050013
			public const int profilePic = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int readOur = 2131034124;
			
			// aapt resource value: 0x7f050036
			public const int red = 2131034166;
			
			// aapt resource value: 0x7f050012
			public const int relativeLayout1 = 2131034130;
			
			// aapt resource value: 0x7f050061
			public const int result = 2131034209;
			
			// aapt resource value: 0x7f05007c
			public const int returnMenu = 2131034236;
			
			// aapt resource value: 0x7f050002
			public const int satellite = 2131034114;
			
			// aapt resource value: 0x7f05006e
			public const int secondIndicator = 2131034222;
			
			// aapt resource value: 0x7f05008a
			public const int signUpViaFacebook = 2131034250;
			
			// aapt resource value: 0x7f05008c
			public const int signUpViaGoogle = 2131034252;
			
			// aapt resource value: 0x7f05008b
			public const int signUpViaTwitter = 2131034251;
			
			// aapt resource value: 0x7f05005b
			public const int startTIme = 2131034203;
			
			// aapt resource value: 0x7f05005e
			public const int teamOne = 2131034206;
			
			// aapt resource value: 0x7f050060
			public const int teamTwo = 2131034208;
			
			// aapt resource value: 0x7f050003
			public const int terrain = 2131034115;
			
			// aapt resource value: 0x7f050074
			public const int textView1 = 2131034228;
			
			// aapt resource value: 0x7f05003f
			public const int textView2 = 2131034175;
			
			// aapt resource value: 0x7f05006f
			public const int thirdIndicator = 2131034223;
			
			// aapt resource value: 0x7f050046
			public const int titleContainer = 2131034182;
			
			// aapt resource value: 0x7f05002e
			public const int top = 2131034158;
			
			// aapt resource value: 0x7f050095
			public const int userContainer = 2131034261;
			
			// aapt resource value: 0x7f05009c
			public const int videoHeading = 2131034268;
			
			// aapt resource value: 0x7f05009a
			public const int videoPic = 2131034266;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutThisApp = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AccountSettings = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ActionBarLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChangePassword = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CustomizingSelction = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CustomizingSelectionCategory = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CustomizingSelectionCategoryCell = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CustomizingSelectionCell = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CustomView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int EditProfile = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ForgotPass = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Gallery = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int GalleryCustomView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ImageTextView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int left_menu = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int left_menu_Unsigned = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LiveScoreCustomView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int LiveScoreTab = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Login = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Main = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int MainCustomView = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int MainMenu = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int MainMenuCustomView = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int MainPicturesCustomView = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int MainTab = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int MenuCustomView = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int NewsDetail = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int NewsScreen = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Notifications = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Picture = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int pictureBlock = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int PictureCustomView = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Pictures = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int PicturesCustomView = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int PicturesMainCustomView = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int RemoveAccount = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int SignUp = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int TodayLiveScore = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int UserCategory = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int Video = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int VideoCustomView = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int VideoDetail = 2130903081;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001c
			public const int app_name = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int auth_client_needs_enabling_title = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int auth_client_needs_installation_title = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int auth_client_needs_update_title = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int auth_client_play_services_err_notification_msg = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int auth_client_requested_by_msg = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int auth_client_using_bad_version_title = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_button = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_text = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_enable_title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_text_phone = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_tablet = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_install_title = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_invalid_account_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_invalid_account_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_network_error_text = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_network_error_title = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_unknown_issue = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_unsupported_date_text = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_unsupported_text = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_unsupported_title = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_update_button = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_text = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_update_title = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int common_signin_button_text = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int common_signin_button_text_long = 2131099667;
			
			// aapt resource value: 0x7f06001b
			public const int hello = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int library_name = 2131099674;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int CustomTitleStyle = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int Theme_Normal = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adUnitId = 1;
			
			public static int[] MapAttrs = new int[] {
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
